### ISSUE TITLE
In LaTeX, ($$  ...) does not render display mode

### ISSUE THREAD

**Issue by saludes** [jsmaniac/scribble-math#4]
Shouldn't this part in **dollar.rkt** be using `style "texMathDisplay"` ?
```
(define math-display-style-latex
  (style "texMathInline"
         (list (tex-addition tex-commands)
               'exact-chars)))
```

**Comment by SuzanneSoy** [comment]
@saludes Fixed, thanks for the report (you were right, that line definitely should have used `texMathDisplay`).
